//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetail
    {
        public int DetailId { get; set; }
        public int TransactionId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public int SellPrice { get; set; }
        public int BuyPrice { get; set; }
    
        public virtual tblTransaction tblTransaction { get; set; }
    }
}
