//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpedition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblExpedition()
        {
            this.tblJoins = new HashSet<tblJoin>();
        }
    
        public int ExpeditionId { get; set; }
        public string ExpeditionName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string AdditionalContact { get; set; }
        public string AdditionalPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJoin> tblJoins { get; set; }
    }
}
