//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJoin
    {
        public int JoinId { get; set; }
        public int ShopId { get; set; }
        public int ExpeditionId { get; set; }
    
        public virtual tblExpedition tblExpedition { get; set; }
        public virtual tblShop tblShop { get; set; }
    }
}
